services:
  bot:
    build: .
    volumes:
      - ./sessions:/app/sessions
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: always
    command: [ "poetry", "run", "python", "src/main.py", "--run-bot" ]
